version: "{build}"

platform:
  - Win32
  - x64

environment:
  MSVC_DEFAULT_OPTIONS: ON
  matrix:
    - msvc: 'Visual Studio 12 2013'
    - msvc: 'Visual Studio 14 2015'

configuration:
  - Debug
  - Release

init:
  - cmd: cmake --version
  - cmd: msbuild /version

clone_folder: C:\projects\ctest

branches:
  only:
    - master

install:
  - git submodule update --init --recursive

before_build:
  - cmd: cd C:\projects\ctest
  - cmd: md build
  - cmd: cd build
  - cmd: if "%platform%"=="Win32" set CMAKE_GENERATOR_NAME=%msvc%
  - cmd: if "%platform%"=="x64"   set CMAKE_GENERATOR_NAME=%msvc% Win64
  - cmd: cmake -G "%CMAKE_GENERATOR_NAME%" ..

build:
  project: C:\projects\ctest\build\u.sln
  verbosity: quiet

test_script:
  - ps: cd C:\projects\ctest\build
  - ctest -VV
